import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
   container:{
      flex:1,
      paddingTop:Platform.OS==="android"?40:0,
      backgroundColor:"#353935"
   },
   headerContainer:{
    flexDirection:"row",
    alignItems:'center',
    justifyContent:"center",
    height:200
   },
   headerText:{
    color:"#ffffff",
    fontWeight:"700",
    fontSize:32,
    letterSpacing:1,
   },
   image:{
    height:350,
    width:400,
    resizeMode:"contain"
   },
   imageContainer:{
    flex:1,
    alignSelf:'center'
   },
   enjoyRideText:{
    textAlign:"center",
    fontWeight:"500",
    fontSize:18,
    color:"#ffffff",
    letterSpacing:2,
   },
   buttonContainer:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
     marginBottom:30,
     backgroundColor:"#4CBB17",
     padding:10,
     margin:15,
   },
   buttonText:{
    textAlign:"center",
    fontWeight:"800",
    fontSize:18,
    color:"#ffffff",
    letterSpacing:2,
   },
   arrowLeft:{
    position:"absolute",
    right:10
   }
});

export default styles;
